# Generated by Django 3.2.7 on 2022-02-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codigo_proveedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
