# Generated by Django 3.2.7 on 2022-02-05 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('codigo_caja', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_caja', models.DateField()),
                ('hora_caja', models.TimeField()),
                ('motivo_caja', models.CharField(max_length=50, null=True)),
                ('entrada_caja', models.CharField(max_length=50, null=True)),
                ('salida_caja', models.CharField(max_length=50, null=True)),
                ('tipo_mov', models.IntegerField(null=True)),
                ('nombre_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.usuariosid')),
            ],
        ),
    ]
