# Generated by Django 3.2.7 on 2022-02-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='codigo_productos',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AddField(
            model_name='sale',
            name='cli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.clientes'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_producto', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('sale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.sale')),
            ],
        ),
    ]
