# Generated by Django 3.2.7 on 2022-02-09 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_productos', models.IntegerField()),
                ('nombre_productos', models.CharField(max_length=50)),
                ('preciocompra_productos', models.IntegerField()),
                ('precioventa_productos', models.IntegerField()),
                ('categoria_productos', models.CharField(max_length=50)),
                ('cantidad_productos', models.IntegerField()),
                ('fecha_productos', models.DateField()),
                ('codigo_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('nombre_proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.proveedor')),
            ],
        ),
    ]
