# Generated by Django 3.2.7 on 2022-02-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
