# Generated by Django 3.2.7 on 2022-02-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0002_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='tipo_mov',
            field=models.IntegerField(null=True),
        ),
    ]
