# Generated by Django 3.2.7 on 2021-11-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0002_usuariosid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
