# Generated by Django 3.2.7 on 2022-02-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0002_auto_20220220_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
