# Generated by Django 3.2.7 on 2022-02-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0002_alter_caja_fecha_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_caja',
            field=models.DateField(),
        ),
    ]
