# Generated by Django 3.2.7 on 2022-02-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0003_alter_caja_fecha_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carrito_id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_carrito', models.IntegerField()),
                ('carrito_producto', models.CharField(max_length=50)),
                ('carrito_precio', models.IntegerField()),
                ('carrito_cantidad', models.IntegerField()),
            ],
        ),
    ]
