# Generated by Django 3.2.7 on 2022-02-23 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0004_sale_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='subtotal',
            new_name='subtotalsuma',
        ),
    ]
