# Generated by Django 3.2.7 on 2022-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0004_clientes2_codigo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioventa_productos',
            field=models.IntegerField(),
        ),
    ]
