# Generated by Django 3.2.7 on 2022-02-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0004_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='total_caja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
