# Generated by Django 3.2.7 on 2022-02-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0004_auto_20220220_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='total_caja',
            field=models.IntegerField(null=True),
        ),
    ]
