# Generated by Django 3.2.7 on 2021-11-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0004_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosid',
            name='tipo_usuario',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
