# Generated by Django 3.2.7 on 2021-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0005_usuariosid_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codigo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=200)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('correo_cliente', models.CharField(max_length=200)),
            ],
        ),
    ]
