# Generated by Django 3.2.7 on 2022-02-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0005_alter_producto_precioventa_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='codigo_productos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vapunto.producto'),
            preserve_default=False,
        ),
    ]
