# Generated by Django 3.2.7 on 2022-02-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0005_caja_total_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='codigo_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='nombre_usuario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_caja',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
