# Generated by Django 3.2.7 on 2022-02-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0005_rename_subtotal_sale_subtotalsuma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='entrada_caja',
            new_name='monto_caja',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='salida_caja',
        ),
    ]
