# Generated by Django 3.2.7 on 2022-02-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0006_auto_20220220_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
