# Generated by Django 3.2.7 on 2022-02-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0006_auto_20220223_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='tipo_mov',
            new_name='estado_caja',
        ),
    ]
