# Generated by Django 3.2.7 on 2021-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0006_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ci_cliente',
            field=models.CharField(default=4484155, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='ruc_cliente',
            field=models.CharField(default=4484155, max_length=50),
            preserve_default=False,
        ),
    ]
