# Generated by Django 3.2.7 on 2022-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0007_auto_20211220_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('codigo_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='ci_cliente',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='correo_cliente',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='direccion_cliente',
        ),
    ]
