# Generated by Django 3.2.7 on 2022-02-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0007_order_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
