# Generated by Django 3.2.7 on 2022-02-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0007_rename_tipo_mov_caja_estado_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='cajaDinero',
            fields=[
                ('codigo_caja_dinero', models.AutoField(primary_key=True, serialize=False)),
                ('total_caja', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='caja',
            name='total_caja',
        ),
    ]
