# Generated by Django 3.2.7 on 2022-02-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0008_alter_order_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.methodpay'),
        ),
        migrations.AlterField(
            model_name='order',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
