# Generated by Django 3.2.7 on 2022-01-13 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0008_auto_20220112_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.ciudad'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.nacionalidad'),
        ),
    ]
