# Generated by Django 3.2.7 on 2022-02-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0008_auto_20220223_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_caja',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caja',
            name='hora_caja',
            field=models.CharField(max_length=50),
        ),
    ]
