# Generated by Django 3.2.7 on 2022-02-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0009_auto_20220221_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioventa_productos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
