# Generated by Django 3.2.7 on 2022-01-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0009_auto_20220112_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('codigo_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('ruc_proveedor', models.IntegerField()),
                ('Telefono_proveedor', models.IntegerField()),
            ],
        ),
    ]
