# Generated by Django 3.2.7 on 2022-02-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0009_auto_20220224_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='hora_caja',
            field=models.TimeField(),
        ),
    ]
