# Generated by Django 3.2.7 on 2022-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0010_alter_producto_precioventa_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='preciocompra_productos',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioventa_productos',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
