# Generated by Django 3.2.7 on 2022-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0011_auto_20220221_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='entrada_caja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='caja',
            name='salida_caja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
