# Generated by Django 3.2.7 on 2022-02-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0012_auto_20220221_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='total_caja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
