# Generated by Django 3.2.7 on 2022-01-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0012_producto_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Proveedor',
            new_name='proveedor',
        ),
    ]
