# Generated by Django 3.2.7 on 2022-01-31 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0013_rename_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes2',
            fields=[
                ('codigo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('ruc_cliente', models.CharField(max_length=50)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=200)),
                ('codigo_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.ciudad')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.nacionalidad')),
            ],
        ),
    ]
