# Generated by Django 3.2.7 on 2022-02-02 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0014_clientes2'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto2',
            fields=[
                ('codigo_productos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_productos', models.CharField(max_length=50)),
                ('preciocompra_productos', models.IntegerField()),
                ('precioventa_productos', models.IntegerField()),
                ('categoria_productos', models.CharField(max_length=50)),
                ('cantidad_productos', models.IntegerField()),
                ('codigo_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.proveedor')),
            ],
        ),
    ]
