# Generated by Django 3.2.7 on 2022-02-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0015_producto2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor2',
            fields=[
                ('codigo_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('ruc_proveedor', models.IntegerField()),
                ('telefono_proveedor', models.IntegerField()),
                ('codigo_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.ciudad')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vapunto.nacionalidad')),
            ],
        ),
    ]
