# Generated by Django 3.2.7 on 2022-02-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0016_proveedor2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad2',
            fields=[
                ('codigo_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=50)),
                ('codigo_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad2',
            fields=[
                ('codigo_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('codigo_usuario', models.IntegerField()),
                ('nombre_usuario', models.CharField(max_length=50)),
            ],
        ),
    ]
