# Generated by Django 3.2.7 on 2022-02-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapunto', '0017_ciudad2_nacionalidad2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad2',
            name='codigo_ciudad',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nacionalidad2',
            name='codigo_nacionalidad',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
